server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    include /etc/nginx/mime.types;

    # [BẮT BUỘC] Cho phép upload file nặng lên tới 50MB
    client_max_body_size 50M;

    # [CẬP NHẬT] Chỉ để những API thật sự tồn tại trong code của bạn.
    location ~ ^/(appointments|auth|courses|programs|survey|users|statistics|files|swagger-ui|v3)(/|$) {
        proxy_pass http://backend:8080;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header Authorization $http_authorization;
    }

    # Xử lý CSS/JS
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        try_files $uri =404;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Xử lý React Router
    location / {
        try_files $uri $uri/ /index.html;
    }
}
